### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sevagh** [kylebgorman/swipe#13]
Hello. I believe when you use fftw3, your code needs to be GPL. Not trying to be Mr. Open Source Lawyer here but I switched out fftw3 for ffts (https://github.com/anthonix/ffts) in some of my own projects to use the MIT license.

**Comment by sevagh** [comment]
In case you're interested: https://github.com/sevagh/swipe/commit/c1942e05d4d2908ffffa0b18c1d836d61dfef5bf

**Comment by kylebgorman** [comment]
Thanks, I would love a PR to fix this! I’ll test that locally and get back
to you shortly.

**Comment by kylebgorman** [comment]
It looks like FFTS isn't available from the Ubuntu repos (yet) and I also
couldn't compile out of the box (it wants me to downgrade aclocal?), so I
am not sure I want to make the move quite yet. And I don't have time to
rewrite or anything like that at the moment; this project has been mature
for almost a decade at this point.

K

**Comment by sevagh** [comment]
FWIW, the aclocal/m4 files in the ffts repository are outdated, and cmake should be used. But, anyway, it makes sense to me to prefer the ubiquitous fftw3.
